whitelist_rules:
  - custom_rules
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_first_not_nil
  - control_statement
  - deployment_target
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - identical_operands
  - implicit_getter
  - implicit_return
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - legacy_random
  - mark
  - modifier_order
  - multiple_closures_with_trailing_closure
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - private_over_fileprivate
  - protocol_property_accessors_order
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - toggle_bool
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - yoda_condition
  - private_action
  - private_outlet
  - closure_body_length
  - cyclomatic_complexity
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - file_length
  - line_length
  - function_body_length
  - type_body_length
  - type_name
  - unused_setter_value
included:
  - BT-Tracking
force_cast: error
force_unwrapping: error
function_body_length:
  - 100 # warning
  - 300 # error
type_body_length:
  - 300 # warning
  - 500 # error
closure_body_length:
  - 200 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
  ignore_comment_only_lines: true
line_length:
  - 160 # warning
  - 320 # error
implicit_return:
  included:
    - getter
    - closure
